site_name: ToggleTVSet
docs_dir: core/components/toggletvset/docs
site_dir: _build/site

repo_url: https://github.com/Jako/ToggleTVSet

pages:
- Home: 'index.md'
- Contributors: 'contributors.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables